---
- name: Convert
  hosts: all
  strategy: free
  become: true
  force_handlers: true
  vars:
    rhsm_username: raul.mejia@guzdan.com
    rhsm_password: R5awu8lp.2023!
    rhsm_org: 17132790
    rhsm_activation_key: conver2rhel

  tasks:
    - name: Perform OS conversion
      ansible.builtin.import_role:
        name: infra.convert2rhel.convert
...
