---
- name: Reboot and Check VM
  hosts: all
  become: yes
  tasks:
    - name: Reboot the machine
      reboot:
        reboot_timeout: 600

    - name: Wait for the machine to come back online
      wait_for_connection:
        timeout: 300

    - name: Check uptime
      command: uptime
      register: uptime_result

    - name: Display uptime
      debug:
        msg: "{{ uptime_result.stdout }}"
